name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: check target
      run: rustup target add x86_64-pc-windows-gnu
    - name: install toolchain
      run: rustup toolchain install stable-x86_64-pc-windows-gnu
    - name: check rust
      run: rustup show
    - name: Build
      run: cargo build --target target.json --release
